# name: Baidu EFE
# url: http://efe.baidu.com
destination: ./_site
plugins:     ./_plugins
markdown: kramdown
permalink: /:title
paginate: 12
paginate_path: "articles/page:num"
encoding: utf-8

post_defaults:
  layout: post

# redcarpet:
#   extensions: ["tables", "autolink", "footnotes"]

kramdown:
  input: GFM
